# web port  properties
server:
  port: 8081
# no web
#spring.main.web-environment=false

# log config
logging:
  config: classpath:logback.xml


### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/job-admin
    executor:
      appname: job-executor
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

